# Generated by Django 2.1 on 2019-12-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0002_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=20)),
                ('c_id', models.ForeignKey(on_delete=True, to='db_test.College')),
            ],
        ),
    ]
