# Generated by Django 2.1 on 2019-12-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0003_college_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_age', models.IntegerField()),
                ('student_phone', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=True, to='db_test.Student')),
            ],
        ),
    ]
