# Generated by Django 2.1 on 2019-12-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0004_studentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
