# Generated by Django 2.1 on 2019-12-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0006_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
    ]
