# Generated by Django 2.1 on 2019-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='db_test.Student'),
        ),
    ]
