# Generated by Django 2.1 on 2019-12-17 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0008_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_test.College'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db_test.Student'),
        ),
    ]
