# Generated by Django 2.1 on 2019-12-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0011_auto_20191219_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='db_test.College'),
        ),
    ]
