# Generated by Django 2.1 on 2019-12-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0013_auto_20191219_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_test.College'),
        ),
    ]
